Connect to API
Smart1-hub/bookstore pull request #4
Opened 2022-06-21 15:55 UTC by Smart1-hub

Add redux-thunk to the project.

Use fetch or axios for making API calls.
Fetch book list from Bookstore API on Books page load.
Refactor add book and remove book features to persist changes in the server.
No styling is required.

2022-06-21 16:06 UTC, ShahierNashaat requested changes
Hi @Smart1-hub , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-21 16:06 UTC, ShahierNashaat commented on src/components/BookItem.js
>      booktitle, id, author, category,
- [ ] Kindly change this from booktitle to title to make it work and display the title of the book.

2022-06-22 08:58 UTC, Smart1-hub reviewed
'Booktitle' in the BookItem.js has been changed to 'title'

2022-06-22 09:12 UTC, BenMukebo approved these changes
### Hi @Smart1-hub, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] I would  recommend adding the issue link in the contributing sections: 

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 09:12 UTC, BenMukebo commented on src/components/AddNewBook.js
> +    } else if (newBook.category === '') {
- [ OPTIONAL] Please add also the validation error message to the author field as you did with the title 😉 👍🏻 
- eg: Please add Book author to submit...

2022-06-22 09:41 UTC, merged